frontend:
  image:
    name: gigpops/fe-applet
    pullPolicy: IfNotPresent
    tag: latest
  port: 3000

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
    


backend:
  image: 
    name: gigpops/be-applet
    pullPolicy: IfNotPresent
    tag: latest
  port: 8000

  autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60


postgres:
  enabled: true
  image:
    name: postgres
    tag: 
  auth:
      host: "postgres"
      # -- Sets postgres username
      user: "sg"
      # -- Sets postgres password
      password: "password"
      # -- Sets postgres port
      port: "5432"
