kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "todo-api.fullname" . }}
  labels:
    app: todo-api-network-policy
spec:
  podSelector:
    matchLabels:
      role: backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
