kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.frontend.labels.app }}-policy
  labels:
    app: {{ .Values.frontend.labels.app }}

    
spec:
  podSelector:
    matchLabels:
      role: frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
      ports:
      - protocol: TCP
        port: 3000
  egress:
    - to:
      ports:
      - protocol: TCP
        port: 8000