kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "todo-list.fullname" . }}
  labels:
    app: todo-list-network-policy
    
spec:
  podSelector:
    matchLabels:
      role: frontend
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 3000