apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.labels.app }}-cm
  labels:
    app: {{ .Values.frontend.labels.app }}
data:
  REACT_APP_BACKEND_API_BASE_URL: http://todo-api.apps.127.0.0.1.nip.io