apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.labels.app }}-service
  labels:
    app: {{ .Values.frontend.labels.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-list.selectorLabels" . | nindent 4 }}
