apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.deploy.name }}-service
  labels:
    app: {{ .Values.backend.labels.app }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
   app: {{ .Values.backend.labels.app }}
