---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.frontend.labels.app }}
  namespace: argocd
spec:
  destination:
    namespace: todo-api
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: build.enabled
          value: "false"
        - name: deploy.route.enabled
          value: "false"
        - name: image.name
          value: quay.io/redhatworkshops/gitops-helm-quarkus
    chart: todo-api
    path: apps/todo-api
    repoURL: 'https://github.com/gitafolabi/devops-tech-challenge.git'
    targetRevision: HEAD
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

