apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.labels.app }}-secrets
  labels:
    app: {{ .Values.postgres.labels.app }}
type: Opaque
data:
    db-password:  {{ .Values.postgres.password | toString | b64enc | quote }}